---
- name: Make sure the {{ db_container_name }} container is created and running
  docker_container:
    name: "{{ db_container_name }}"
    image: "deluan/ryot:latest"
    pull: yes
    state: "started"
    env:
      "PUID": "{{ guid }}"
      "PGID": "{{ guid }}"
      "TZ": "{{ timezone }}"
      "VIRTUAL_HOST": "ryot.box"
    volumes:
      - "{{ docker_dir }}/{{ db_container_name }}:/data"
      - "/media/Media/Music:/music"
      - "/etc/localtime:/etc/localtime:ro"
    restart_policy: always
    ports:
      - 4533:4533
    exposed_ports:
      - 8096
- name: Make sure the {{ container_name }} container is created and running
  docker_container:
    name: "{{ container_name }}"
    image: "deluan/ryot:v7"
    pull: yes
    state: "started"
    env:
      "PUID": "{{ guid }}"
      "PGID": "{{ guid }}"
      "TZ": "{{ timezone }}"
      "VIRTUAL_HOST": "ryot.box"
      "ScanSchedule": "@every 24h"
    volumes:
      - "{{ docker_dir }}/{{ container_name }}:/data"
      - "/media/Media/Music:/music"
      - "/etc/localtime:/etc/localtime:ro"
    restart_policy: always
    ports:
      - 8080:8090
    exposed_ports:
      - 8090
