---
- name: Make sure the couchdb container is created and running
  docker_container:
    name: "{{ container_name }}"
    image: "couchdb:3.5.1"
    pull: yes
    privileged: no
    labels:
      "flame.type": "application"
      "flame.name": "{{ container_name | title }}"
      "flame.url": "{{ dashboard_url }}"
      "flame.icon": "custom"
    state: 'started'
    restart_policy: always
    env:
      "PUID": "{{ guid }}"
      "PGID": "{{ guid }}"
      "TZ": "{{ timezone }}"
      "VPN_USER": "{{ vpn_user }}"
      "VPN_PASS": "{{ vpn_pass }}"
      "VIRTUAL_HOST": "couchdb.home"
      "VIRTUAL_PORT": "5984"
      "COUCHDB_USER": "{{ couchdb_user }}"
      "COUCHDB_PASSWORD": "{{ couchdb_pass }}"
      "COUCHDB_DATABASE": "obsidian"
    ports:
      - "5984:5984"
    volumes:
      - "{{ docker_dir }}/{{ container_name }}/data:/opt/couchdb/data"
      - "/etc/localtime:/etc/localtime:ro"
